### PR TITLE
Upgrade for v0.0.4

### PR DESCRIPTION
**Pull request by dirkx**
Minor tweak (prefix is HC1: instead of HC1 to preserve privacy / leaking to google & siri.

Brings it in line with this mornging version of v.0.0.4 of the spec.

### CODE REVIEW

**Comment by yspreen** [comment]
Thank you for the PR! Do you have a source for spec 0.0.4? It hasn't made its way over to our dev teams.

**Comment by dirkx** [comment]
https://github.com/ehn-digital-green-development/hcert-spec/blob/v105/hcert_spec.md

**Comment by yspreen** [comment]
Got it, I can see the changed prefix. We'll have to align with our project leads because they define the spec we build. But as far as I know, the spec you shared is our goal. I'll work to align our specs with that one, and then we can merge. Thanks again

**Comment by yspreen** [comment]
@dirkx Sorry, my clean up of feature branches automatically closed this. Could you open again with develop as base?

**Comment by yspreen** [comment]
Recreated and merged as #16

**Pull request closed without merging**
